#!/bin/bash
Jo=$1
str=$2
read -ra ADDR <<< "$str" 
chemin_binaire=""
if test $Jo -eq 0; then
        echo "nope"
else
        variable=$(ls /var/Eurecom/inputaflpp | wc -l)
        variable=$(($variable/$Jo))
        counter=0
        mkdir "/var/Eurecom/inputaflppV1"
        mkdir "/var/Eurecom/outputaflppV1"
        while (( counter < Jo ))
        do
                path="/var/Eurecom/inputaflppV1/$counter"
                mkdir "$path"
                path2="/var/Eurecom/outputaflppV1/$counter"
                mkdir "$path2"
                ls /var/Eurecom/inputaflpp | tail -n $variable > file
                var1="$(pwd)/file"
                while IFS= read -r line 
                do 
                        mv "/var/Eurecom/inputaflpp/$line" "$path/"
                done < "$var1"
                counter=$(($counter+1))
        done
        echo "reached here"
        ctr=0
        IFS=' '
        while(( ctr < Jo ))
        do
                njeh="/var/Eurecom/inputaflppV1/$ctr"
                tarhouni="/var/Eurecom/outputaflppV1/$ctr"
                zab=0
                dhia="${ADDR[$zab]}"
                zab=3
                please="0"
                while (( "$please" == "0" ))
                do
                        firas=$(($zab-1))
                        if [ "${ADDR[$firas]}" == "-i" ]
                        then

                                dhia="${dhia} ${ADDR[$firas]}"
                                dhia="${dhia} ${njeh}"
                                firas=$(($firas+2))
                                zab=$(($firas+1))
                        elif [ "${ADDR[$firas]}" == "-o" ]
                        then
                                dhia="${dhia} ${ADDR[$firas]}"
                                dhia="${dhia} ${tarhouni}"
                                firas=$(($firas+2))
                                zab=$(($firas+1))
                        else
                                dhia="${dhia} ${ADDR[$firas]}"
                                firas=$(($firas+1))
                                zab=$(($firas+1))
                        fi
                        if test "${ADDR[$zab]}" == ""; then
                                please=1
                        fi

                done
                echo "hama"

        ctr=$(($ctr+1))
        ola=${ADDR[$firas]}
        dhia="${dhia} ${ola} &"
        eval "$dhia"
        done 

fi
